let Atar = [
    {
        image : "images/All Products/Atar/1MillionType.jpeg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/212men.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/acqua-di-gio-final-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/aseel-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/AVENTUS-CREED-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/creed-viking-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/dunhill-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/eternal-love-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/fahrenheit-final-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/HUGO-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/invictus-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/janan_-1_2_-300x300.webp",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/MUSK-SILK-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/oud-ispahan-final-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/Sauvage-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/Atar/zarar01-300x300.webp",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    
]


let allPocketPerfumes = [
    {
        image : "images/All Products/All Pocket Perfumes/212-Men-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/212-sexy-men-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Acqua-Di-Gio-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Acqua-Di-Gio-Black-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Allure-Homme-Sport-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Aramis-1-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Armani-Oud-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Armani-pour-homme-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/ARMANI-PRIVE-OUD-ROYAL-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Africa-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Alaska-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Anti-Hangover-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Apollo-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Click-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Dark-Temptation-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Deep-Space-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Excite-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Gold-Temptation-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Marine-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Mature-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Peace-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Signature-Intense-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Signature-Mysterious-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Signature-Rogue-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Signature-Suave-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Axe-Sport-Blast-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/azzaro-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Bleu-De-Chanel-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Blue-for-men-2-b20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Blue-Lady-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Bvlgari-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Bvlgari-Aqva-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Calvin-Klein-Man-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Chance-Chanel-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Chanel-No5-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/CK-in-2-U-Him-2-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/CK-One-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Cool-Water-M-Davidoff-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Creed-Silver-Mountain-Water-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Dune-Dior-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Dunhill-Desire-Black-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Dunhill-Icon-Gold-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Dunhill-Icon-Silver-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Emotion-Rasasi-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Escada-Espcially-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Escape-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Eternity-For-Men-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Euphoria-CK-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/EUPHORIA-LIQUID-GOLD-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/FAHRENHEIT-DIOR-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Ferrari-Black-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/FERRARI-RED-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/GABRIELLE-CHANEL-PARIS-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Gucci-by-Gucci-Brown-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/GUCCI-BY-GUCCI-POUR-HOMME-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Gucci-Eau-De-Pink-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Gucci-Guilty-1-B20-1-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Gucci-Oud-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Gucci-Rush-1-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Hugo-boss-bottled-2-B20.-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/HUGO-BOSS-ICED-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Hugo-boss-Man-2-B20.-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Hugo-Women-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Issey-Miyake-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/JAGUAR-PRESTIGE-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Jagur-Classic-Black-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Joop-Homme-2-B20.-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Jovan-Musk-Men-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Lacoste-Red-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Lacoste-Touch-of-Pink-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Lacoste-White-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/MICHAEL-KORS-SPORTY-CITRUC-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Mont-Blanc-Emblem-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Mont-Blanc-Emblem-Absolu-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Mont-Blanc-Emblem-intense-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Mont-Blanc-Individuel-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/MY-BURBERRY-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/One-Man-show-Gold-Edition-2-b20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Oud-Ispahan-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/packof4-760.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/packof5-900.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/PACK43-300x300.png",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Paco-Rabanne-1-Million-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Pasha-DE-Cartier-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Pleasure-Estee-Lauder-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Poeme-Lancome-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Poison-Dior-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/POLO-BLACK-RALPH-LAUREN-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Polo-Blue-Ralph-Lauren-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Polo-Ralph-Lauren-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Romance-Ralph-Lauren-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/ROYALE-RASASI-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Screat-1-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Silver-shadow-Attitude-2-b20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Still-Jennifer-Lopez-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Terre-De-Hermes-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Tom-ford-Black-Orchid-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Tom-ford-Noir-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Tom-ford-Oud-Wood-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/TOM-FORD-SOLEIL-BLANC-2-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Tom-ford-Velvet-Orchid-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Tommy-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Tommy-Girl-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "images/All Products/All Pocket Perfumes/Versace-Bright-Crystal-2-B20-300x300.jpg",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    
    
]


let mensPerfume = [
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    
]
let pocketPerfumes = [
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    
]
let pureAtar = [
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    
]
let unisexPerfumes = [
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    
]
let womensPerfumes = [
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    {
        image : "",
        brand : "  ",
        product : "  ",
        price : " ",
    },
    
]


let brandedPocketPerfumes = [
    {
        image : "",
        brand : " ",
        product : " ",
        price : " ",
    },
    {
        image : "",
        brand : " ",
        product : " ",
        price : " ",
    },
    
]
